version: '3'
services:
  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
