version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongo-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - long-network

  redis:
    image: redis
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - long-network

networks:
  long-network: