@urldev=http://localhost:3066/v1/api
## signup
POST  {{urldev}}/shop/signup/
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273

{
    "name": "longcv",
    "email": "longcv@mcivietnam.com",
    "password": "long123456"
}

### loginn
POST  {{urldev}}/shop/login/
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781


{
    "email": "longcv@mcivietnam.com",
    "password": "long123456"
}


### logout
POST  {{urldev}}/logout
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:65155eb2bd98746dbdc3c029
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE1NGUwMjNlOGY4ZGU1OTIwODMwODYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NTg5OTk4MSwiZXhwIjoxNjk2MDcyNzgxfQ.OJggsXWw9LerWLLVhxFGtOmYJeIM-z0ycbwXlktJUpjzq9eoQk4VWWxOkbiQxDREhX_Wa54prqXUMVlFe-0wTU84cTlRcRE6aVmAc8dbAYEJb4MI_PFS6utD_ZuORFkjNvkO1jm6B5WaXabn_9LrgeLIwDjVWpNn5blJM7r18N5Lq1CQXBKWbOSx80YzkX4aKdBqCgEZ9FcWXfIy1Q-Z8snsuOnwoC0In0WS2G--juUxrF0dIkiRo1ILZKKFQPUucCB7eu6Lb2GKDhj4J9fLpz2EY9pfwo9jC0UlKLjeY5_RVRJqUoSNOzwE6AOa_RP997o3yM0vnf4qvAsK3yFfhQM0lZIDTZA9I2wyxJ03jZw1YXzwU14zLAAETERARieq3mNqczO02blG3YdWtCWcv4EiJPI6QyKjeqzT1JonMtiBn0P8Q0sqXP_rabcGL6KUTJEvZo4nXSyonEqNRaw_VFx-4fEO5q91_WVMqb15P3j6IDJ7i3yDP9y0SiS3PTCe85LRl02aCqqb2bhYHoHADJOUxD7Oy-StLKVi4itXjbxx7WIa_7PeHoPb8QMsDVLhNK9ubu748MA6TY9htqFkp1UUCdaR7GtEIQgVneMwqCGaAA0htdii2OXZ4W1d-Ib8QH2dTln53rhx2LflgEVtRf4SNK5HlAXiOHJ8SotwKtw


### handle refreshToken
POST  {{urldev}}/shop/handleRefreshToken/
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273
client-id:6518eee9315fe44f76558edc
refreshtoken:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE4ZWVlOTMxNWZlNDRmNzY1NThlZGMiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjI0ODQ0OCwiZXhwIjoxNjk2ODUzMjQ4fQ.QNEKxcrshCCh128WbAxFWh_5KgjfPIOmGhkFEAiKdOSGF2QFmUP3EpZ-aGH4YX3COA3A7zQTMYa7TDwPWR5d8aqm0qEJbKPgbBmruanrctRaM36C58Tb5CINkksh7Vmm_B8GceVQZCZ3mWfmEVTUieJjNy09n048_DxfFQ6_5fj1ZKmR6TwbUk3tPO4o-uTiBQuVImoH6TQR-aYEqC9nLJmI46r2FNJO6hb4QsQDXL4fz1e6ZOccajnDpT__hoJwAQyuDXszgWCnDc7MPaD-glvz2NQfrnpyABkzfQXOAFuBqT8E7Ia2buqIJRLAMN3L6g8wdC9D6yf6erHfikJnTwQFtqhGuGItgKfx0VDOlKYzG3yZxahxrhQykH5iddnkZebmkFVXD299BB60WUI-pmtwW8ILYTRhqIx1FaZZvLxFD0ccPEDfVb5BB_3Uz5Z23tz9LX_HJDLyirxpfE3J4kiy4dNnvwEKrsOQPYu8ZenemL_DcA5y9spyn_ntzk1gYS5A2bMka10VWEo4BPYDI66gLhepRXOFN9kU07VoL_ZKJdZumh34qMdMa6r_40QEnjv-FIziYbum5hjXSfpCUs6vdndEzF2RkbgiBb1CQMQ06bgbI6mN2C14RGmOvmEmeDih7nRAiuvaxLDPHH21ylMfehV6mvpgJ9XNUL-ggOA



###

POST  {{urldev}}/product/create-product
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:6517a2f273ed26c89a99d96f
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE3YTJmMjczZWQyNmM4OWE5OWQ5NmYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjI2MzQ1OCwiZXhwIjoxNjk2NDM2MjU4fQ.S0XITm4JSl7qd-EpWtQ1KNM7ku52eG_Uw5sb81oOYwy0aPAC4jsi7NZ5mmdQLsSBQacekbMb54rWER4ISV6ioXxdYqax-Y4sE4fOX-Sdmbh0U0GD74VMk64pJ2anFjrb0WFjzO8Bu2yCEit0TCOiOfrI-9mHjtxg-_QQfG5z3jeiynuEugdNVwaeARsFa4bNfVPcI1zrqyACxnyB1aWlUVtj-RWgtofd9Dhz3hrZC0qwip3nLTDk4wV8KPC9DkfVZtT6EeY42EAYbAk_9dvY_4pLSuiYiRV2jXIOaFr4KiVg6lK6W-rghw7TA-NxXr_eaeSEaENDSZVON-YfF0Rggtg7d8xIdnKFrmayyVLOXF_QgLWvQ4XbOEpiMoeVgi9myh3TuA32NZkcQMDXHN6X9HGEDo360Cgw60tex8hRjvoUHD4v-twYNorP9PfrQGVGnGZ6aF9VaOaMuw8A0Iy3D26YEDi4IGKWi8m2Z_ekWb9TA9BbCSOc1EaOItRmyOHao-fXH0YDhOM84pobmVbi1llDbdhmabX33trfhA_ZCGFLEeu34o46Eq7zrJglBLsk4w40KL4blxPxHvSRmxDO763rg01CoKKEtImh3ndJjAEwRkZI5KFfDGeE6hPZECJrBxY9nITy1eTHDLx27b1LO76Iu5xn5RsGh4oOMPm-JA0

{
    "product_name": "New Jeans",
    "product_thumb":  "product Thumb",
    "product_description": "Hight=quality jeans",
    "product_price": "50",
    "product_quantity": "5",
    "product_type": "Clothing",
    "product_shop": "6517a2f273ed26c89a99d96f",
    "product_attributes": {
        "brand": "levi 5",
        "size": "L",
        "material": "denim"
    }
}

###
GET  {{urldev}}/product/drafts/all
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:6517a2f273ed26c89a99d96f
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE3YTJmMjczZWQyNmM4OWE5OWQ5NmYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjgyMjYzNywiZXhwIjoxNjk2OTk1NDM3fQ.FZeNTXDGdZCEsf0SqCBUwEMrS9sEvoAtOr4L1AlknMEynW-c2W6uHLQHglolH8CWFszyy52GdJxE6rL_I8tXypFYh02S63IUtegxY499H3Q4X9laFfHwyGuBBB-VkVYxGIKHWOUgWtxjz9yXX2BYDm-8NtSovk-NibdgKVoIihQNQIfX9PZwHwx7X1v4Cra71BglF9ZM8mHzw5AYUCT2QHvf8-kjU34N-Uyq2oYttCems21WXvFCRF2O1ga-rdB57gV-AThXEPeiiZwAvt9PDTSpDDWbpiImaXaPL0WkQjLSe93_s-ANiDGvhAPFMILVK3b5QbdD0TDVHBfovYBl7NKD84r4TSfIo_KkmuE9Qmt3fj36umK4vT3xjZH5kRidrIjVu9ccWkJahfAy6FZJV0Cf4cJITfGMuOuMUWN3Jr8C2VVOphwdzTCu6uvc_56UAJbGE1yVnicIhxDcipCS4RvjjdetblUsFEvhRzSnH47Yg3of5DSTyC7r-O6yTYqx1RfKYQQp9V3N7mhtV4g9yhfWnuXzW7KjWkwWy6wvTDdn6_cdJAYxqxIfGWSEx4ROUXdwWHii4y83XvDrJUe2al6lCV48SWUQIjo0bc9X0GKpdvNqMpw-nmnicfCRNANE4dQleknPKJiu0jOL410Td0kCeubXHqSBpmK6h0EzhmQ

###
GET  {{urldev}}/product/publish/all
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:6517a2f273ed26c89a99d96f
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE3YTJmMjczZWQyNmM4OWE5OWQ5NmYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjU4NDEyNywiZXhwIjoxNjk2NzU2OTI3fQ.ahmOoJApuW-JUmsxwJx9hOWjiBu9LiiSK0GhPKaXY6IWQEx60-lauqSd-_YCoYSIwdO4QuIKIONprwUyFNhi3tqYNsPDxtN28f5hv3S5Hb-xpF4CEVBoyobi1hmEJ4uEZZUGGeT7s-9mULoy7dQhLB9B4BtL33Ubzi1KX-VMumVNy1sNxbrEwGmc4mVPKXQCjeoJ4QHpOQc2UGNvwMHTgzAzAbiJegYLCxg9Xo1wb3HVg3Pivj5kNTqXr5aDnEgCmp0Ojm56pJZoQCWfsp_WKuZwVanlROG3DhuJbuKddfkExA565nx-hLvretiMewIizXVwv2w9V0uLknV-sl2Ar1NoqkrW4SKEqW_JVNHLnGV-CtlAGdC3Pc-ikhbdk0yfp0AS8MQZynQ7tE3TW-Pl0ZWycDnlJX3ZDQENxXPfazXDWQ3MDEVSYlHjP7AxniJQ2cgEyB_K5nSmwBC565fXH6xZVv5Q0qdUEGKyFrwf1FCUdRWsjtLyTLCafm0dfax8Eas5ML66B7mA_N6SFVE3eX1g6_peBguWMi8Alh9KzdAQVzhnrsInVG952T4Qivavw_iQn2z7w4pydIAF6GEkTtiz4STcXvhNO7AyMcMY1SALKTIFZwACGGvqbkP24lG693tGHfQ_MOeOmkdU5tYjRW9sK5etd2gfRVUqpoGT6Tk

###
POST   {{urldev}}/product/publish-product-by-shop/651ba39e39c4668a8d7eba8b
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:6517a2f273ed26c89a99d96f
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE3YTJmMjczZWQyNmM4OWE5OWQ5NmYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjU4NDEyNywiZXhwIjoxNjk2NzU2OTI3fQ.ahmOoJApuW-JUmsxwJx9hOWjiBu9LiiSK0GhPKaXY6IWQEx60-lauqSd-_YCoYSIwdO4QuIKIONprwUyFNhi3tqYNsPDxtN28f5hv3S5Hb-xpF4CEVBoyobi1hmEJ4uEZZUGGeT7s-9mULoy7dQhLB9B4BtL33Ubzi1KX-VMumVNy1sNxbrEwGmc4mVPKXQCjeoJ4QHpOQc2UGNvwMHTgzAzAbiJegYLCxg9Xo1wb3HVg3Pivj5kNTqXr5aDnEgCmp0Ojm56pJZoQCWfsp_WKuZwVanlROG3DhuJbuKddfkExA565nx-hLvretiMewIizXVwv2w9V0uLknV-sl2Ar1NoqkrW4SKEqW_JVNHLnGV-CtlAGdC3Pc-ikhbdk0yfp0AS8MQZynQ7tE3TW-Pl0ZWycDnlJX3ZDQENxXPfazXDWQ3MDEVSYlHjP7AxniJQ2cgEyB_K5nSmwBC565fXH6xZVv5Q0qdUEGKyFrwf1FCUdRWsjtLyTLCafm0dfax8Eas5ML66B7mA_N6SFVE3eX1g6_peBguWMi8Alh9KzdAQVzhnrsInVG952T4Qivavw_iQn2z7w4pydIAF6GEkTtiz4STcXvhNO7AyMcMY1SALKTIFZwACGGvqbkP24lG693tGHfQ_MOeOmkdU5tYjRW9sK5etd2gfRVUqpoGT6Tk

###
POST   {{urldev}}/product/unpublish-product-by-shop/651ba39e39c4668a8d7eba8b
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:6517a2f273ed26c89a99d96f
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE3YTJmMjczZWQyNmM4OWE5OWQ5NmYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjU4NDEyNywiZXhwIjoxNjk2NzU2OTI3fQ.ahmOoJApuW-JUmsxwJx9hOWjiBu9LiiSK0GhPKaXY6IWQEx60-lauqSd-_YCoYSIwdO4QuIKIONprwUyFNhi3tqYNsPDxtN28f5hv3S5Hb-xpF4CEVBoyobi1hmEJ4uEZZUGGeT7s-9mULoy7dQhLB9B4BtL33Ubzi1KX-VMumVNy1sNxbrEwGmc4mVPKXQCjeoJ4QHpOQc2UGNvwMHTgzAzAbiJegYLCxg9Xo1wb3HVg3Pivj5kNTqXr5aDnEgCmp0Ojm56pJZoQCWfsp_WKuZwVanlROG3DhuJbuKddfkExA565nx-hLvretiMewIizXVwv2w9V0uLknV-sl2Ar1NoqkrW4SKEqW_JVNHLnGV-CtlAGdC3Pc-ikhbdk0yfp0AS8MQZynQ7tE3TW-Pl0ZWycDnlJX3ZDQENxXPfazXDWQ3MDEVSYlHjP7AxniJQ2cgEyB_K5nSmwBC565fXH6xZVv5Q0qdUEGKyFrwf1FCUdRWsjtLyTLCafm0dfax8Eas5ML66B7mA_N6SFVE3eX1g6_peBguWMi8Alh9KzdAQVzhnrsInVG952T4Qivavw_iQn2z7w4pydIAF6GEkTtiz4STcXvhNO7AyMcMY1SALKTIFZwACGGvqbkP24lG693tGHfQ_MOeOmkdU5tYjRW9sK5etd2gfRVUqpoGT6Tk

###
GET   {{urldev}}/product/search/New jean
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781

###
GET   {{urldev}}/product/
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781

###
GET   {{urldev}}/product/651ba39e39c4668a8d7eba8b
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
