@urldev=http://localhost:3066/v1/api
## signup
POST  {{urldev}}/shop/signup/
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273

{
    "name": "longcv",
    "email": "longcv@mcivietnam.com",
    "password": "long123456"
}

### loginn
POST  {{urldev}}/shop/login/
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273


{
    "email": "longcv@mcivietnam.com",
    "password": "long123456"
}


### logout
POST  {{urldev}}/logout
Content-Type: application/json
x-api-key:4dafabbe1300a262a6160b30e9a05c80187e786fec0a70c4f49b6901faf97fa83b2fbe8e9bc5e0e629f7a6ac82bccb06c103282b7a035119557f5ec9a4cb3781
client-id:65155eb2bd98746dbdc3c029
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE1NGUwMjNlOGY4ZGU1OTIwODMwODYiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NTg5OTk4MSwiZXhwIjoxNjk2MDcyNzgxfQ.OJggsXWw9LerWLLVhxFGtOmYJeIM-z0ycbwXlktJUpjzq9eoQk4VWWxOkbiQxDREhX_Wa54prqXUMVlFe-0wTU84cTlRcRE6aVmAc8dbAYEJb4MI_PFS6utD_ZuORFkjNvkO1jm6B5WaXabn_9LrgeLIwDjVWpNn5blJM7r18N5Lq1CQXBKWbOSx80YzkX4aKdBqCgEZ9FcWXfIy1Q-Z8snsuOnwoC0In0WS2G--juUxrF0dIkiRo1ILZKKFQPUucCB7eu6Lb2GKDhj4J9fLpz2EY9pfwo9jC0UlKLjeY5_RVRJqUoSNOzwE6AOa_RP997o3yM0vnf4qvAsK3yFfhQM0lZIDTZA9I2wyxJ03jZw1YXzwU14zLAAETERARieq3mNqczO02blG3YdWtCWcv4EiJPI6QyKjeqzT1JonMtiBn0P8Q0sqXP_rabcGL6KUTJEvZo4nXSyonEqNRaw_VFx-4fEO5q91_WVMqb15P3j6IDJ7i3yDP9y0SiS3PTCe85LRl02aCqqb2bhYHoHADJOUxD7Oy-StLKVi4itXjbxx7WIa_7PeHoPb8QMsDVLhNK9ubu748MA6TY9htqFkp1UUCdaR7GtEIQgVneMwqCGaAA0htdii2OXZ4W1d-Ib8QH2dTln53rhx2LflgEVtRf4SNK5HlAXiOHJ8SotwKtw


### handle refreshToken
POST  {{urldev}}/shop/handleRefreshToken/
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273
client-id:6518eee9315fe44f76558edc
refreshtoken:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE4ZWVlOTMxNWZlNDRmNzY1NThlZGMiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjI0ODQ0OCwiZXhwIjoxNjk2ODUzMjQ4fQ.QNEKxcrshCCh128WbAxFWh_5KgjfPIOmGhkFEAiKdOSGF2QFmUP3EpZ-aGH4YX3COA3A7zQTMYa7TDwPWR5d8aqm0qEJbKPgbBmruanrctRaM36C58Tb5CINkksh7Vmm_B8GceVQZCZ3mWfmEVTUieJjNy09n048_DxfFQ6_5fj1ZKmR6TwbUk3tPO4o-uTiBQuVImoH6TQR-aYEqC9nLJmI46r2FNJO6hb4QsQDXL4fz1e6ZOccajnDpT__hoJwAQyuDXszgWCnDc7MPaD-glvz2NQfrnpyABkzfQXOAFuBqT8E7Ia2buqIJRLAMN3L6g8wdC9D6yf6erHfikJnTwQFtqhGuGItgKfx0VDOlKYzG3yZxahxrhQykH5iddnkZebmkFVXD299BB60WUI-pmtwW8ILYTRhqIx1FaZZvLxFD0ccPEDfVb5BB_3Uz5Z23tz9LX_HJDLyirxpfE3J4kiy4dNnvwEKrsOQPYu8ZenemL_DcA5y9spyn_ntzk1gYS5A2bMka10VWEo4BPYDI66gLhepRXOFN9kU07VoL_ZKJdZumh34qMdMa6r_40QEnjv-FIziYbum5hjXSfpCUs6vdndEzF2RkbgiBb1CQMQ06bgbI6mN2C14RGmOvmEmeDih7nRAiuvaxLDPHH21ylMfehV6mvpgJ9XNUL-ggOA



###

POST  {{urldev}}/product/create-product
Content-Type: application/json
x-api-key:3ef7ebfa0f29bfae6c17054076783edba1c63abf9e6fe3d09a88ad1347d0b155254cc573c1e47ef5df1008334f0f9b91ca8798328ab60905942956197d240273
client-id:6518eee9315fe44f76558edc
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE4ZWVlOTMxNWZlNDRmNzY1NThlZGMiLCJlbWFpbCI6ImxvbmdjdkBtY2l2aWV0bmFtLmNvbSIsImlhdCI6MTY5NjEzMjg0MiwiZXhwIjoxNjk2MzA1NjQyfQ.kmctCd0KKHwCflr5UkTpoz8jn6JQVoQaeO6vEeEHruhZGxWrUj5JiHhSYrxmYhsvGAhKTBpUzu9_4qm5VLJ8zxhL-lMJyhlQt7-NH1y7n2Kf8EdWMoPWEXp7cacGTV2qT9GcRTA8v1uqkrqB4yixTnU4kelHvZ7KIeAKkELJHq4NehzNeUpuo-d8W-v6hGeyfeoF5jaY0F9d66wCbYm3H4tvHeBY4MQOWwk98VyHIV2zzi1etObZpsvghv7jYvSePJLHE8VJ9tRzBYIp9hFB-qvEq4k1z5fpKiTffblxqygje9BgxIVAJO8oEg1M1V2X-LsTOtLX8x7G1drxgTZ9MhgaV4DeLtsV9K_brdbslEIqmLFo9dIdKWmcMM0DFFQpoK4gJkgcqITW3lbByOAEWhuGqcS6tsTUsc0eCSOIdakX3-ejar8TakHs5nW-9KC5pO8zQMdkXNForNVvcegZe8sCXciZ7BY6IdV7gvbwPz09t91Ka2oHATBt1e6FfgZxwza8kRCpaaqKJJ0JWi2_DBzZ8l2LRUG-Nal9259zs9I_G32miwjgFtIpvC8Xh1w0jzDuSPt9dhYAlwYfLUYmC7Jwpr24PtQrYUqybHB2Z_gUm75nTWZvbq-JYa72VO9-HcegmkMx_3hKf6eF_-C5MsQHNQeHS8IEE8OJaxaURdM

{
    "product_name": "New Jeans",
    "product_thumb":  "product Thumb",
    "product_description": "Hight=quality jeans",
    "product_price": "50",
    "product_quantity": "5",
    "product_type": "Clothing",
    "product_shop": "6518eee9315fe44f76558edc",
    "product_attributes": {
        "brand": "levi 5",
        "size": "L",
        "material": "denim"
    }
}
